name: Build forsikringsavtale

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'liberica'
            java-version: '21'
      - run: ./gradlew build
      - run: docker compose build
